services:
  configserver:
    image: "andre21funcap/configserver:s8"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent http://localhost:8071/actuator/health/readiness | grep UP || exit"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends: 
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "andre21funcap/accounts:s8"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends: 
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: "andre21funcap/loans:s8"
    container_name: loans-ms
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends: 
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: "andre21funcap/cards:s8"
    container_name: cards-ms
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: "cards"
    extends: 
      file: common-config.yml
      service: microservice-configserver-config

networks:
  eazyBank:
    driver: bridge