build:
  version: "1.0"

cards:
  message: "Welcome to EazyBank cards related prod APIs 2"
  contactDetails:
    name: "Andr√© Lucas - product owner"
    email: "mail@email.com"
  onCallSupport:
    - (111) 321-1234
    - (111) 123-1345