spring:
 config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

loans:
  message: "Welcome to EazyBank loans related prod APIs "
  contactDetails:
    name: "Andr√© Lucas - product owner"
    email: "mail@email.com"
  onCallSupport:
    - (111) 321-1234
    - (111) 123-1345