services:
  configserver:
    image: "karma21/configserver:s8"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent http://localhost:8071/actuator/health/readiness | grep UP || exit"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends: 
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: "karma21/eurekaserver:s8"
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail --silent http://localhost:8070/actuator/health/readiness | grep UP || exit"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  accounts:
    image: "karma21/accounts:s8"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends: 
      file: common-config.yml
      service: microservice-eureka-config

  loans:
    image: "karma21/loans:s8"
    container_name: loans-ms
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends: 
      file: common-config.yml
      service: microservice-eureka-config

  loans2:
    image: "karma21/loans:s8"
    container_name: loans-ms2
    ports:
      - "8091:8090"
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends: 
      file: common-config.yml
      service: microservice-eureka-config

  cards:
    image: "karma21/cards:s8"
    container_name: cards-ms
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: "cards"
    extends: 
      file: common-config.yml
      service: microservice-eureka-config

networks:
  eazyBank:
    driver: bridge